language: c
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev

script:
  - mkdir -p ../libuast-build && cd ../libuast-build && cmake ../libuast && make && make test
  - cd $TRAVIS_BUILD_DIR

before_deploy:
  - sh scripts/update-minor.sh
  - git archive --output libuast.tar.gz `git stash create`

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: libuast.tar.gz
  skip_cleanup: true
  on:
    tags: true
